# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 136e81c39fe3ad125e4efc069f27285062a59c404bf48c8c2c68aa37bf98198bc47ee9a0cda612a1ec95a194370cc28359df3f357108f70e4e087130ddfaff46

test:
  secret_key_base: 5b318799b2e3cc09155c7000ab347e55f8242037c96aca1f8d613810e97aea7d24008f0ca4a95a00b58dad31bd18ac1dcd2ad890791ad60e0c6475c10ce5b34f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
